### ISSUE TITLE
Composer dependcies illuminate/support

### ISSUE THREAD

**Issue by blpraveen** [novay/laravel-avatar#1]
I am getting this error

Root composer.json requires novay/laravel-avatar ^1.0 -> satisfiable by novay/laravel-avatar[v1.0].
    - novay/laravel-avatar v1.0 requires illuminate/support ~5.2 -> found illuminate/support[v5.2.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by novay** [comment]
composer require novay/laravel-avatar "^1.1"
